openapi: 3.0.0
info:
  version: 1.0.0
  title: sirius
paths:
  /lpas/{uid}/scans:
    get:
      summary: Retrieve LPA and Continuation Sheet scans
      description: Retrieves the LPA and Continuation Sheet scans for the specified UID
      parameters:
        - in: path
          name: uid
          description: The UID of the LPA
          required: true
          schema:
            type: string
            pattern: '^7\d{11}$'
            example: '700000000003'
      responses:
        '200':
          description: OK
          content:
            application/json:
              examples:
                lpa0047:
                  value:
                    lpaScans: [{'location': 's3://opg-backoffice-datastore-local/LP1H-Scan.pdf', 'template': 'LP1H'}, {'location': 's3://opg-backoffice-datastore-local/LPA120.pdf', 'template': 'LPA'}]
                    continuationSheets: [{'location': 's3://opg-backoffice-datastore-local/LPC-LP-Scan.pdf', 'template': 'LPC'}]
                lpa0138:
                  value:
                    lpaScans: [{'location': 's3://opg-backoffice-datastore-local/LP1F-Scan.pdf', 'template': 'LP1F'}]
                    continuationSheets: [{'location': 's3://opg-backoffice-datastore-local/LPC-Scan.pdf', 'template': 'LPC'}, {'location': 's3://opg-backoffice-datastore-local/LPC2-Scan.pdf', 'template': 'LPC'}]
                lpa0088:
                  value:
                    lpaScans: [{'location': 's3://opg-backoffice-datastore-local/PFA117-Scan.pdf', 'template': 'LPA117'}]
                lpa0089:
                  value:
                    lpaScans: [{'location': 's3://opg-backoffice-datastore-local/HW114-Scan.pdf', 'template': 'LPA114'}]
                    continuationSheets: [{'location': 's3://opg-backoffice-datastore-local/PFA-C-Scan.pdf', 'template': 'LPC'}]
                lpa0090:
                  value:
                    lpaScans: [{'location': 's3://opg-backoffice-datastore-local/LPA-PW-Scan.pdf', 'template': ''}]
                    continuationSheets: [{'location': 's3://opg-backoffice-datastore-local/Correspondence-Bad-Continuation-Scan.pdf', 'template': 'Correspondence'}]
                lpa0091:
                  value:
                    lpaScans: [{'location': 's3://opg-backoffice-datastore-local/LP1F-LP-Scan.pdf', 'template': ''}]
                    continuationSheets: [{'location': 's3://opg-backoffice-datastore-local/LPC-LP-Scan.pdf', 'template': 'LPC'}]
                lpa0092:
                  value:
                    lpaScans: [{'location': 's3://opg-backoffice-datastore-local/PFA117-Scan.pdf', 'template': 'LPA117'}, {'location': 's3://opg-backoffice-datastore-local/Correspondence-Bad-Continuation-Scan.pdf', 'template': 'Correspondence'}]
                lpa0093:
                  value:
                    lpaScans: [{'location': 's3://opg-backoffice-datastore-local/LPA-ContinuationSheets-working-barcode-LP1F.tiff', 'template': ''}]
                    continuationSheets: [{'location': 's3://opg-backoffice-datastore-local/LPA-ContinuationSheets-working-barcode-LP1F.tiff', 'template': 'LP1F'}]
                lpa0094:
                  value:
                    lpaScans: [{'location': 's3://opg-backoffice-datastore-local/LPA-ContinuationSheets-broken-barcode-LP1F.pdf', 'template': ''}]
                    continuationSheets: [{'location': 's3://opg-backoffice-datastore-local/LPA-ContinuationSheets-broken-barcode-LP1F.pdf', 'template': 'LP1F'}]
                lpa0095:
                  value:
                    lpaScans: [{'location': 's3://opg-backoffice-datastore-local/LPA-ContinuationSheets-working-barcode-LP1F.pdf', 'template': ''}]
                    continuationSheets: [{'location': 's3://opg-backoffice-datastore-local/LPA-ContinuationSheets-working-barcode-LP1F.pdf', 'template': 'LP1F'}]
                lpa0096:
                  value:
                    lpaScans: [{'location': 's3://opg-backoffice-datastore-local/LPA-prefs-only-plus-continuation-broken-LP1F.pdf', 'template': ''}]
                    continuationSheets: [{'location': 's3://opg-backoffice-datastore-local/LPA-prefs-only-plus-continuation-broken-LP1F.pdf', 'template': 'LP1F'}]
                lpa0097:
                  value:
                    lpaScans: [{'location': 's3://opg-backoffice-datastore-local/LPA-prefs-only-plus-continuation-working-LP1F.pdf', 'template': ''}]
                    continuationSheets: [{'location': 's3://opg-backoffice-datastore-local/LPA-prefs-only-plus-continuation-working-LP1F.pdf', 'template': 'LP1F'}]
              schema:
                type: object
                properties:
                  lpaScans:
                    type: array
                    items:
                      type: object
                      properties:
                        location:
                          type: string
                          format: uri
                        template:
                          type: string
                  continuationSheets:
                    type: array
                    items:
                      type: object
                      properties:
                        location:
                          type: string
                          format: uri
                        template:
                          type: string
                required:
                  - lpaScans
                  - continuationSheets
        '404':
          description: Document not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        '400':
          description: Bad request (either in parameter or payload)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
components:
  schemas:
    Error400:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              code:
                type: string
                example: "OPGDATA-API-INVALIDREQUEST"
              title:
                type: string
                example: "Invalid Request"
              detail:
                type: string
                example: "Invalid request, the data is incorrect"
              meta:
                type: object
                properties:
                  x-ray:
                    type: string
                    example: "93c330d4-7d84-4c1b-8fdb-54cec5bfe747"
    Error404:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              code:
                type: string
                example: "OPGDATA-API-NOTFOUND"
              title:
                type: string
                example: "Page not found"
              detail:
                type: string
                example: "That URL is not a valid route, or the item resource does not exist"
              meta:
                type: object
                properties:
                  x-ray:
                    type: string
                    example: "93c330d4-7d84-4c1b-8fdb-54cec5bfe747"
